"""Add auto_reply column to Message

Revision ID: 2aaeb0b7c6cf
Revises: 967ee5b59230
Create Date: 2023-05-19 01:06:49.281696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aaeb0b7c6cf'
down_revision = '967ee5b59230'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_reply', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('auto_reply')

    # ### end Alembic commands ###
